source 'https://cdn.cocoapods.org/'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'profile_exchange' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'GoogleSignIn'
	pod 'GoogleSignInSwift'
	pod 'FirebaseCore'
	pod 'FirebaseAuth'	

  # Pods for profile_exchange

  target 'profile_exchangeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'profile_exchangeUITests' do
    # Pods for testing
  end

end
